// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type CreatePostInput struct {
	Title    *string `json:"title,omitempty"`
	Content  string  `json:"content"`
	ImageURL *string `json:"imageURL,omitempty"`
	AudioURL *string `json:"audioURL,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Post struct {
	ID        string    `json:"id"`
	UserID    string    `json:"userID"`
	Title     *string   `json:"title,omitempty"`
	Content   string    `json:"content"`
	ImageURL  *string   `json:"imageURL,omitempty"`
	AudioURL  *string   `json:"audioURL,omitempty"`
	ParentID  *string   `json:"parentID,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Likes     int       `json:"likes"`
	Reposts   int       `json:"reposts"`
	Children  []*Post   `json:"children"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}
