// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	packages "github.com/bertoxic/graphql_chat/packages"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// GetUserByName provides a mock function with given fields: ctx, username
func (_m *UserRepo) GetUserByName(ctx context.Context, username string) (packages.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByName")
	}

	var r0 packages.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (packages.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) packages.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(packages.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
